'use client';

import { useState } from 'react';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import FadeInSection from '@/components/FadeInSection';
import {
  ThumbsDown,
  CircleCheckBig,
  MoveRight,
  HardHat,
  GitBranch,
  Scaling,
  Puzzle,
  CircleHelp,
  Landmark,
  ShoppingCart,
  Lightbulb,
  X,
} from 'lucide-react';
import Link from 'next/link';

const problemSolutionPairs = [
  {
    problem: {
      icon: ThumbsDown,
      heading: 'The Comparison Flaw',
      description:
        'Traditional accounting forces executives to compare lines of code to legal risk and sales dollars, leading to fictional, gut-driven investment decisions.',
    },
    solution: {
      icon: CircleCheckBig,
      heading: 'The BVU Solution',
      subtitle: 'Normalized Investment',
      description:
        'The BVU Model abstracts every team\'s output into a single, universal metric (BVU), enabling direct, objective investment comparison across all functions—from IT to Sales.',
    },
  },
  {
    problem: {
      icon: ThumbsDown,
      heading: 'The Cost Center Trap',
      description:
        'Teams like IT, HR, and Internal Legal are seen only as expenses. Their essential contributions (risk reduction, efficiency) are unquantifiable, making them targets for arbitrary budget cuts.',
    },
    solution: {
      icon: CircleCheckBig,
      heading: 'The BVU Solution',
      subtitle: 'Auditable Value Stream',
      description:
        'It transforms non-commercial functions from expense items into auditable value producers, where investment is justified by the measurable BVUs generated per staff hour and dollar spent.',
    },
  },
  {
    problem: {
      icon: ThumbsDown,
      heading: 'The Misaligned Activity Trap',
      description:
        'Teams focus on clearing a queue (e.g., tickets, feature requests) quickly, regardless of whether that activity produces low-value outcomes, leading to significant wasted effort.',
    },
    solution: {
      icon: CircleCheckBig,
      heading: 'The BVU Solution',
      subtitle: 'Strategic Prioritization',
      description:
        'By measuring the BVU generated by specific activities within a team\'s mandate, leadership can surgically shift resources away from high-volume, low-value work and focus effort on the activities that deliver the greatest enterprise return.',
    },
  },
];

const mechanicsCards = [
  {
    icon: HardHat,
    heading: 'BVU Calibration',
    description:
      'The initial process involves defining the measurable output of every team (e.g., lines of code, tickets closed, renewal contracts). This output is then normalized against cost to establish the initial Cost-Per-BVU Baseline for cross-organizational comparison.',
  },
  {
    icon: GitBranch,
    heading: 'Integration with I-O Architecture',
    description:
      'The BVU Model works independently, but its precision is amplified when integrated with the I-O Architecture Model. I-O\'s Fixed-Scope Work Units provide the clear, verifiable, and consistent outputs necessary to perform the BVU normalization and cost analysis with the highest accuracy.',
  },
  {
    icon: Scaling,
    heading: 'Strategic Benefit: Capital Allocation',
    description:
      'Executives can shift from arbitrary budget decisions to fact-based Capital Allocation, investing in teams and specific activities that demonstrably produce the greatest number of BVUs for the enterprise.',
  },
  {
    icon: Puzzle,
    heading: 'Strategic Benefit: Risk Hedging',
    description:
      'The model quantifies the protective value of non-commercial teams (e.g., Legal, Security), allowing leadership to see investment in these areas not as a cost, but as a direct form of Risk Hedging that secures the entire value stream.',
  },
];

const coreConcepts = [
  {
    term: 'Value Abstraction',
    definition:
      'The foundational mathematical process of normalizing the diverse, tangible outputs of all teams (e.g., risk mitigated, tickets solved, dollars earned) into a single, unified, and quantifiable metric established as a consistent management convention.',
  },
  {
    term: 'Business Value Unit (BVU)',
    definition:
      'The fundamental, normalized metric that represents a single, abstracted unit of organizational value, used as a stable unit of account for internal comparison.',
  },
  {
    term: 'Cost-Per-BVU Baseline',
    definition:
      'The initial financial calculation derived by dividing a team\'s total operational cost over a defined period by the total number of normalized BVUs produced. This metric establishes the baseline cost efficiency for comparative analysis across different functional areas.',
  },
  {
    term: 'BVU-Per-Personnel Hour/Spend',
    definition:
      'A key operational metric that quantifies performance by dividing total BVU output by the team\'s total operational spend or time. This granular calculation accounts for disparities in staff cost and utilization, precisely identifying where personnel investment yields the highest measurable return.',
  },
  {
    term: 'Value Equivalence',
    definition:
      'The principle that, after the initial calibration process, one BVU generated by a commercial team (e.g., sales) is treated as equivalent in organizational importance to one BVU generated by a non-commercial team (e.g., legal or IT infrastructure).',
  },
  {
    term: 'Enterprise Value Stream',
    definition:
      'The complete organizational workflow seen through the lens of BVU generation, allowing leadership to map and analyze which functional areas and specific activities—rather than just which products—generate the highest return on enterprise value.',
  },
  {
    term: 'Activity Prioritization',
    definition:
      'The strategic mechanism of using BVU analysis to identify high-volume, low-value work efforts within a team\'s mandate. This allows management to surgically shift resources away from inefficient processes to focus strictly on activities that deliver the greatest BVU return.',
  },
];

const modalSteps = [
  {
    label: 'Establishing the Currency',
  },
  {
    label: 'Define BVU for Each Output',
  },
  {
    label: 'BVU-Per-Personnel Hour',
  },
  {
    label: 'Executive Decision',
  },
];

export default function BusinessValueUnitModel() {
  const [showModal, setShowModal] = useState(false);
  const [activeStep, setActiveStep] = useState(0);

  return (
    <main className="relative w-full min-h-screen overflow-x-hidden bg-white">
      <Header />

      {/* Section 1: Hero */}
      <FadeInSection delay={0} direction="up" animateOnInitialView>
        <div
          className="w-full px-6"
          style={{
            paddingTop: 'clamp(100px, 9.86vw, 142px)',
            paddingBottom: 'clamp(80px, 8vw, 120px)',
            backgroundColor: '#F9FAFB',
          }}
        >
          <div className="text-center mx-auto" style={{ maxWidth: 'min(900px, 90%)' }}>
            <p
              className="font-dm-sans font-bold text-[#14358A] uppercase tracking-wide mb-4"
              style={{
                fontSize: 'clamp(12px, 1.07vw, 15.4px)',
                letterSpacing: '0.77px',
              }}
            >
              The Business Value Unit (BVU) Model
            </p>

            <h1
              className="font-dm-sans font-bold tracking-[-0.03em] text-[#14358A] mb-6"
              style={{
                fontSize: 'clamp(32px, 3.5vw, 56px)',
                lineHeight: '105%',
              }}
            >
              The End of Arbitrary Capital Allocation
            </h1>

            <p
              className="font-dm-sans font-normal text-[#68718B]"
              style={{
                fontSize: 'clamp(15px, 1.375vw, 19.8px)',
                lineHeight: '1.6',
              }}
            >
              The Business Value Unit (BVU) Model is a proprietary financial framework that solves the most critical flaw in modern finance: the failure to quantify the contribution of non-commercial teams. We translate all diverse internal outputs (from risk mitigation and compliance to efficiency gains) into a single, normalized abstraction of value. The BVU Model eliminates "apples-to-oranges" comparisons, transforming support functions from unquantifiable cost centres into auditable, high-yield investment platforms.
            </p>
          </div>
        </div>
      </FadeInSection>

      {/* Section 2: Problem/Solution Pairs */}
      <FadeInSection direction="up">
        <div
          className="w-full px-6"
          style={{
            paddingTop: 'clamp(60px, 6vw, 100px)',
            paddingBottom: 'clamp(60px, 6vw, 100px)',
          }}
        >
          <div className="mx-auto" style={{ maxWidth: 'min(1300px, 92%)' }}>
            <h2
              className="font-dm-sans font-bold tracking-[-0.03em] text-[#14358A] mb-6"
              style={{
                fontSize: 'clamp(24px, 2.75vw, 39.6px)',
                lineHeight: '105%',
              }}
            >
              The Unquantified Cost of Flawed Executive Decisions
            </h2>

            <p
              className="font-dm-sans font-normal text-[#68718B] mb-12"
              style={{
                fontSize: 'clamp(15px, 1.375vw, 19.8px)',
                lineHeight: '1.6',
                maxWidth: '800px',
              }}
            >
              Traditional business metrics fail to capture the true value of non-commercial teams, leading to flawed decision-making and wasted resources.
            </p>

            <div className="space-y-8">
              {problemSolutionPairs.map((pair, idx) => (
                <div key={idx} className="grid md:grid-cols-2 gap-8 items-stretch">
                  {/* Problem Card */}
                  <FadeInSection direction="left" delay={idx * 0.05}>
                    <div
                      className="rounded-xl border shadow-lg p-6 flex flex-col h-full"
                      style={{
                        backgroundColor: 'rgba(220, 38, 38, 0.05)',
                        borderColor: 'rgba(220, 38, 38, 0.2)',
                      }}
                    >
                      <div className="flex items-center gap-3 mb-4">
                        <ThumbsDown size={24} color="#DC2626" strokeWidth={1.5} />
                        <h3
                          className="font-dm-sans font-bold tracking-[-0.03em] text-[#DC2626]"
                          style={{
                            fontSize: 'clamp(16px, 1.6vw, 22px)',
                            lineHeight: '120%',
                            margin: 0,
                          }}
                        >
                          {pair.problem.heading}
                        </h3>
                      </div>
                      <p
                        className="font-dm-sans font-normal text-[#68718B]"
                        style={{
                          fontSize: 'clamp(15px, 1.375vw, 19.8px)',
                          lineHeight: '140%',
                        }}
                      >
                        {pair.problem.description}
                      </p>
                    </div>
                  </FadeInSection>

                  {/* Solution Card */}
                  <FadeInSection direction="right" delay={idx * 0.05}>
                    <div
                      className="rounded-xl border shadow-lg p-6 flex flex-col h-full"
                      style={{
                        backgroundColor: 'rgba(20, 53, 138, 0.05)',
                        borderColor: 'rgba(20, 53, 138, 0.2)',
                      }}
                    >
                      <div className="flex items-center gap-3 mb-4">
                        <CircleCheckBig size={24} color="#14358A" strokeWidth={1.5} />
                        <div>
                          <h3
                            className="font-dm-sans font-bold tracking-[-0.03em] text-[#14358A]"
                            style={{
                              fontSize: 'clamp(16px, 1.6vw, 22px)',
                              lineHeight: '120%',
                              margin: 0,
                            }}
                          >
                            {pair.solution.heading}
                          </h3>
                          <p
                            className="font-dm-sans font-semibold text-[#14358A]"
                            style={{
                              fontSize: 'clamp(13px, 1.11vw, 16px)',
                              lineHeight: '120%',
                              margin: 0,
                            }}
                          >
                            {pair.solution.subtitle}
                          </p>
                        </div>
                      </div>
                      <p
                        className="font-dm-sans font-normal text-[#68718B]"
                        style={{
                          fontSize: 'clamp(15px, 1.375vw, 19.8px)',
                          lineHeight: '140%',
                        }}
                      >
                        {pair.solution.description}
                      </p>
                    </div>
                  </FadeInSection>
                </div>
              ))}
            </div>
          </div>
        </div>
      </FadeInSection>

      {/* Section 3: BVU Model in Practice */}
      <FadeInSection direction="up">
        <div
          className="w-full px-6"
          style={{
            paddingTop: 'clamp(60px, 6vw, 100px)',
            paddingBottom: 'clamp(60px, 6vw, 100px)',
            backgroundColor: '#F9FAFB',
          }}
        >
          <div className="text-center mx-auto" style={{ maxWidth: 'min(900px, 90%)' }}>
            <h2
              className="font-dm-sans font-bold tracking-[-0.03em] text-[#14358A] mb-6"
              style={{
                fontSize: 'clamp(24px, 2.75vw, 39.6px)',
                lineHeight: '105%',
              }}
            >
              The BVU Model in Practice
            </h2>

            <p
              className="font-dm-sans font-normal text-[#333333] mb-8"
              style={{
                fontSize: 'clamp(15px, 1.375vw, 19.8px)',
                lineHeight: '1.6',
              }}
            >
              The real power of the BVU model is in its practical application. It transforms abstract theories about value into concrete, data-driven decisions.
            </p>

            <button
              onClick={() => setShowModal(true)}
              className="inline-flex items-center gap-2 font-dm-sans font-medium text-white rounded-[8px] transition-opacity hover:opacity-90"
              style={{
                backgroundColor: '#14358A',
                fontSize: 'clamp(15px, 1.375vw, 19.8px)',
                padding: '12px 28px',
              }}
            >
              Too theoretical? Click to see the BVU model in action. <MoveRight size={20} />
            </button>
          </div>
        </div>
      </FadeInSection>

      {/* Modal */}
      {showModal && (
        <div
          className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4"
          style={{ top: 0, left: 0, right: 0, bottom: 0, display: 'flex', alignItems: 'center', justifyContent: 'center' }}
          onClick={() => setShowModal(false)}
        >
          <div
            className="bg-white rounded-lg shadow-2xl w-full max-w-5xl max-h-[90vh] overflow-hidden flex flex-col"
            onClick={(e) => e.stopPropagation()}
          >
            {/* Modal Header */}
            <div
              className="border-b p-6 flex items-center justify-between flex-shrink-0"
              style={{ backgroundColor: '#F9FAFB' }}
            >
              <div>
                <p
                  className="font-dm-sans font-bold text-[#14358A] uppercase tracking-wide mb-2"
                  style={{
                    fontSize: 'clamp(12px, 1.07vw, 15.4px)',
                    letterSpacing: '0.77px',
                  }}
                >
                  A Real-World Scenario
                </p>
                <h2
                  className="font-dm-sans font-bold tracking-[-0.03em] text-[#14358A]"
                  style={{
                    fontSize: 'clamp(20px, 2.2vw, 32px)',
                    lineHeight: '105%',
                  }}
                >
                  IT Enablement vs. Sales Funding Decision
                </h2>
              </div>
              <button
                onClick={() => setShowModal(false)}
                className="text-gray-500 hover:text-gray-700 transition-colors flex-shrink-0"
              >
                <X size={24} />
              </button>
            </div>

            {/* Modal Content */}
            <div className="flex-1 overflow-y-auto p-6">
              <div className="grid md:grid-cols-[250px_1fr] gap-8 h-full">
                {/* Left: Step Nav */}
                <div className="space-y-2">
                  {modalSteps.map((step, idx) => (
                    <button
                      key={idx}
                      onClick={() => setActiveStep(idx)}
                      className="w-full text-left p-4 rounded-lg transition-all font-dm-sans font-medium"
                      style={{
                        backgroundColor: activeStep === idx ? '#14358A' : '#F9FAFB',
                        color: activeStep === idx ? 'white' : '#333333',
                        fontSize: 'clamp(14px, 1.22vw, 17.6px)',
                        lineHeight: '120%',
                      }}
                    >
                      {idx + 1}. {step.label}
                    </button>
                  ))}
                </div>

                {/* Right: Content Panel */}
                <div className="overflow-y-auto">
                  {/* Step 0: Establishing the Currency */}
                  {activeStep === 0 && (
                    <div>
                      <h3
                        className="font-dm-sans font-bold tracking-[-0.03em] text-[#14358A] mb-4"
                        style={{
                          fontSize: 'clamp(18px, 1.8vw, 26px)',
                          lineHeight: '120%',
                        }}
                      >
                        Establishing the Currency
                      </h3>
                      <p
                        className="font-dm-sans font-normal text-[#68718B] mb-6"
                        style={{
                          fontSize: 'clamp(15px, 1.375vw, 19.8px)',
                          lineHeight: '1.6',
                        }}
                      >
                        Before the comparison, leadership agrees on a baseline: <strong>'1 BVU = $100 of organizational value.'</strong> This is a strategic convention, not an absolute calculation. It establishes the consistent unit needed to compare disparate functions.
                      </p>
                      <ul
                        className="space-y-3 font-dm-sans font-normal text-[#68718B]"
                        style={{
                          fontSize: 'clamp(14px, 1.22vw, 17.6px)',
                          lineHeight: '1.6',
                        }}
                      >
                        <li>• IT's risk mitigation and time savings are modeled to deliver 7,500 units of this value.</li>
                        <li>• Sales's pipeline acceleration is modeled to deliver 5,000 units of this value.</li>
                        <li>• With a shared currency, we can now calculate which project delivers more value per dollar invested.</li>
                      </ul>
                    </div>
                  )}

                  {/* Step 1: Define BVU for Each Output */}
                  {activeStep === 1 && (
                    <div>
                      <h3
                        className="font-dm-sans font-bold tracking-[-0.03em] text-[#14358A] mb-6"
                        style={{
                          fontSize: 'clamp(18px, 1.8vw, 26px)',
                          lineHeight: '120%',
                        }}
                      >
                        Define BVU for Each Output
                      </h3>
                      <table
                        className="w-full border-collapse"
                        style={{
                          fontSize: 'clamp(13px, 1.11vw, 16px)',
                          lineHeight: '1.6',
                        }}
                      >
                        <thead>
                          <tr style={{ borderBottom: '2px solid #14358A' }}>
                            <th
                              className="text-left p-3 font-dm-sans font-bold text-[#14358A]"
                              style={{ fontSize: 'clamp(14px, 1.22vw, 17.6px)' }}
                            >
                              Team
                            </th>
                            <th
                              className="text-left p-3 font-dm-sans font-bold text-[#14358A]"
                              style={{ fontSize: 'clamp(14px, 1.22vw, 17.6px)' }}
                            >
                              Tangible Output
                            </th>
                            <th
                              className="text-left p-3 font-dm-sans font-bold text-[#14358A]"
                              style={{ fontSize: 'clamp(14px, 1.22vw, 17.6px)' }}
                            >
                              BVU Abstraction
                            </th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr style={{ borderBottom: '1px solid #E5E7EB' }}>
                            <td className="p-3 font-dm-sans font-normal text-[#68718B]">IT Infrastructure</td>
                            <td className="p-3 font-dm-sans font-normal text-[#68718B]">Reduced Login Failure Time</td>
                            <td className="p-3 font-dm-sans font-normal text-[#68718B]">1 BVU = $X in productivity returned & risk avoided</td>
                          </tr>
                          <tr>
                            <td className="p-3 font-dm-sans font-normal text-[#68718B]">Sales Enablement</td>
                            <td className="p-3 font-dm-sans font-normal text-[#68718B]">Time Saved Searching</td>
                            <td className="p-3 font-dm-sans font-normal text-[#68718B]">1 BVU = $Y in selling time returned (tied to pipeline value)</td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  )}

                  {/* Step 2: BVU-Per-Personnel Hour */}
                  {activeStep === 2 && (
                    <div>
                      <h3
                        className="font-dm-sans font-bold tracking-[-0.03em] text-[#14358A] mb-6"
                        style={{
                          fontSize: 'clamp(18px, 1.8vw, 26px)',
                          lineHeight: '120%',
                        }}
                      >
                        BVU-Per-Personnel Hour Calculation
                      </h3>
                      <table
                        className="w-full border-collapse"
                        style={{
                          fontSize: 'clamp(13px, 1.11vw, 16px)',
                          lineHeight: '1.6',
                        }}
                      >
                        <thead>
                          <tr style={{ borderBottom: '2px solid #14358A' }}>
                            <th
                              className="text-left p-3 font-dm-sans font-bold text-[#14358A]"
                              style={{ fontSize: 'clamp(13px, 1.11vw, 16px)' }}
                            >
                              Project
                            </th>
                            <th
                              className="text-left p-3 font-dm-sans font-bold text-[#14358A]"
                              style={{ fontSize: 'clamp(13px, 1.11vw, 16px)' }}
                            >
                              Annual Output
                            </th>
                            <th
                              className="text-left p-3 font-dm-sans font-bold text-[#14358A]"
                              style={{ fontSize: 'clamp(13px, 1.11vw, 16px)' }}
                            >
                              Total BVU
                            </th>
                            <th
                              className="text-left p-3 font-dm-sans font-bold text-[#14358A]"
                              style={{ fontSize: 'clamp(13px, 1.11vw, 16px)' }}
                            >
                              Cost
                            </th>
                            <th
                              className="text-left p-3 font-dm-sans font-bold text-[#14358A]"
                              style={{ fontSize: 'clamp(13px, 1.11vw, 16px)' }}
                            >
                              Cost/BVU
                            </th>
                          </tr>
                        </thead>
                        <tbody>
                          <tr style={{ borderBottom: '1px solid #E5E7EB' }}>
                            <td className="p-3 font-dm-sans font-normal text-[#68718B]">IT (SSO)</td>
                            <td className="p-3 font-dm-sans font-normal text-[#68718B]">Prevents 40,000 hrs downtime + security risk</td>
                            <td className="p-3 font-dm-sans font-normal text-[#68718B]">750,000 BVUs</td>
                            <td className="p-3 font-dm-sans font-normal text-[#68718B]">$1.5M</td>
                            <td className="p-3 font-dm-sans font-bold" style={{ color: '#10B981' }}>
                              $2.00 ✓
                            </td>
                          </tr>
                          <tr>
                            <td className="p-3 font-dm-sans font-normal text-[#68718B]">Sales Enablement</td>
                            <td className="p-3 font-dm-sans font-normal text-[#68718B]">Returns 25,000 hrs rep time + pipeline growth</td>
                            <td className="p-3 font-dm-sans font-normal text-[#68718B]">500,000 BVUs</td>
                            <td className="p-3 font-dm-sans font-normal text-[#68718B]">$1.5M</td>
                            <td className="p-3 font-dm-sans font-bold" style={{ color: '#DC2626' }}>
                              $3.00 ✗
                            </td>
                          </tr>
                        </tbody>
                      </table>
                    </div>
                  )}

                  {/* Step 3: Executive Decision */}
                  {activeStep === 3 && (
                    <div>
                      <h3
                        className="font-dm-sans font-bold tracking-[-0.03em] text-[#14358A] mb-6"
                        style={{
                          fontSize: 'clamp(18px, 1.8vw, 26px)',
                          lineHeight: '120%',
                        }}
                      >
                        Executive Decision
                      </h3>
                      <p
                        className="font-dm-sans font-normal text-[#68718B] mb-6"
                        style={{
                          fontSize: 'clamp(15px, 1.375vw, 19.8px)',
                          lineHeight: '1.6',
                        }}
                      >
                        The executive team uses the Cost-Per-BVU Baseline to make a fact-based decision. The IT Infrastructure project delivers the same unit of standardized, comparable value (the BVU) at a <strong>33% lower cost ($2.00 vs. $3.00)</strong>.
                      </p>
                      <div
                        className="rounded-xl border p-6"
                        style={{
                          backgroundColor: 'rgba(16, 185, 129, 0.05)',
                          borderColor: 'rgba(16, 185, 129, 0.2)',
                        }}
                      >
                        <div className="flex items-start gap-4">
                          <CircleCheckBig size={32} color="#10B981" strokeWidth={1.5} className="flex-shrink-0" />
                          <div>
                            <h4
                              className="font-dm-sans font-bold tracking-[-0.03em] text-[#10B981] mb-2"
                              style={{
                                fontSize: 'clamp(16px, 1.6vw, 22px)',
                                lineHeight: '120%',
                              }}
                            >
                              Result: IT Infrastructure Gets the Funding
                            </h4>
                            <p
                              className="font-dm-sans font-normal text-[#68718B]"
                              style={{
                                fontSize: 'clamp(14px, 1.22vw, 17.6px)',
                                lineHeight: '1.6',
                              }}
                            >
                              The IT Infrastructure project receives the funding because it is the most efficient generator of enterprise value, regardless of its "cost center" label. The investment is justified because it is the best use of capital to secure and optimize the entire organization's ability to produce value.
                            </p>
                          </div>
                        </div>
                      </div>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* Section 4: Mechanics and Strategic Benefits */}
      <FadeInSection direction="up">
        <div
          className="w-full px-6"
          style={{
            paddingTop: 'clamp(60px, 6vw, 100px)',
            paddingBottom: 'clamp(60px, 6vw, 100px)',
          }}
        >
          <div className="mx-auto" style={{ maxWidth: 'min(1300px, 92%)' }}>
            <h2
              className="font-dm-sans font-bold tracking-[-0.03em] text-[#14358A] mb-12"
              style={{
                fontSize: 'clamp(24px, 2.75vw, 39.6px)',
                lineHeight: '105%',
              }}
            >
              Mechanics and Strategic Benefits
            </h2>

            <p
              className="font-dm-sans font-normal text-[#68718B] mb-12"
              style={{
                fontSize: 'clamp(15px, 1.375vw, 19.8px)',
                lineHeight: '1.6',
                maxWidth: '800px',
              }}
            >
              The BVU Model is both a measurement framework and a strategic tool for capital allocation and risk management.
            </p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-stretch">
              {mechanicsCards.map((card, idx) => {
                const Icon = card.icon;
                return (
                  <FadeInSection key={idx} delay={idx * 0.05}>
                    <div
                      className="rounded-xl border shadow-lg p-6 flex flex-row items-start gap-4 hover:shadow-xl transition-shadow duration-300 h-full"
                      style={{
                        backgroundColor: '#FFFFFF',
                        borderColor: '#E5E7EB',
                      }}
                    >
                      <Icon size={24} color="#14358A" strokeWidth={1.5} className="flex-shrink-0 mt-1" />
                      <div>
                        <h3
                          className="font-dm-sans font-bold tracking-[-0.03em] text-[#14358A] mb-3"
                          style={{
                            fontSize: 'clamp(16px, 1.6vw, 22px)',
                            lineHeight: '120%',
                          }}
                        >
                          {card.heading}
                        </h3>
                        <p
                          className="font-dm-sans font-normal text-[#68718B]"
                          style={{
                            fontSize: 'clamp(14px, 1.22vw, 17.6px)',
                            lineHeight: '140%',
                          }}
                        >
                          {card.description}
                        </p>
                      </div>
                    </div>
                  </FadeInSection>
                );
              })}
            </div>
          </div>
        </div>
      </FadeInSection>

      {/* Section 5: Managing Performance Over Time */}
      <FadeInSection direction="up">
        <div
          className="w-full px-6"
          style={{
            paddingTop: 'clamp(60px, 6vw, 100px)',
            paddingBottom: 'clamp(60px, 6vw, 100px)',
            backgroundColor: '#F9FAFB',
          }}
        >
          <div className="text-center mx-auto" style={{ maxWidth: 'min(900px, 90%)' }}>
            <p
              className="font-dm-sans font-bold text-[#14358A] uppercase tracking-wide mb-4"
              style={{
                fontSize: 'clamp(12px, 1.07vw, 15.4px)',
                letterSpacing: '0.77px',
              }}
            >
              Beyond a Single Metric
            </p>

            <h2
              className="font-dm-sans font-bold tracking-[-0.03em] text-[#14358A] mb-6"
              style={{
                fontSize: 'clamp(24px, 2.75vw, 39.6px)',
                lineHeight: '105%',
              }}
            >
              Managing Performance Over Time
            </h2>

            <p
              className="font-dm-sans font-normal text-[#333333] mb-8"
              style={{
                fontSize: 'clamp(15px, 1.375vw, 19.8px)',
                lineHeight: '1.6',
              }}
            >
              The real power of the BVU is not in a one-time calculation. It is in creating a stable benchmark to track efficiency trends. Once calibrated, you can see if a team's Cost-Per-BVU is improving quarter-over-quarter, or if a new process generates more BVUs per personnel hour. It turns abstract goals into a continuous performance dashboard.
            </p>

            <Link
              href="/our-solutions"
              className="inline-flex items-center gap-2 font-dm-sans font-medium transition-opacity hover:opacity-80"
              style={{
                color: '#14358A',
                fontSize: 'clamp(15px, 1.375vw, 19.8px)',
              }}
            >
              See it in Action <MoveRight size={20} />
            </Link>
          </div>
        </div>
      </FadeInSection>

      {/* Section 6: Core Concepts */}
      <FadeInSection direction="up">
        <div
          className="w-full px-6"
          style={{
            paddingTop: 'clamp(60px, 6vw, 100px)',
            paddingBottom: 'clamp(60px, 6vw, 100px)',
          }}
        >
          <div className="mx-auto" style={{ maxWidth: 'min(1300px, 92%)' }}>
            <h2
              className="font-dm-sans font-bold tracking-[-0.03em] text-[#14358A] mb-12"
              style={{
                fontSize: 'clamp(24px, 2.75vw, 39.6px)',
                lineHeight: '105%',
              }}
            >
              Core Concepts of the BVU Model
            </h2>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 items-stretch">
              {coreConcepts.map((concept, idx) => (
                <FadeInSection key={idx} delay={idx * 0.05}>
                  <div
                    className="rounded-lg p-6 hover:bg-white hover:shadow-lg transition-all duration-300 text-center h-full flex flex-col items-center justify-center"
                    style={{
                      border: '1px solid #E5E7EB',
                      backgroundColor: '#F9FAFB',
                    }}
                  >
                    <CircleHelp size={24} color="#14358A" strokeWidth={1.5} className="mx-auto mb-4" />
                    <h3
                      className="font-dm-sans font-bold tracking-[-0.03em] text-[#14358A] mb-3"
                      style={{
                        fontSize: 'clamp(16px, 1.6vw, 22px)',
                        lineHeight: '120%',
                      }}
                    >
                      {concept.term}
                    </h3>
                    <p
                      className="font-dm-sans font-normal text-[#68718B]"
                      style={{
                        fontSize: 'clamp(14px, 1.22vw, 17.6px)',
                        lineHeight: '140%',
                      }}
                    >
                      {concept.definition}
                    </p>
                  </div>
                </FadeInSection>
              ))}
            </div>
          </div>
        </div>
      </FadeInSection>

      {/* Section 7: CTA */}
      <FadeInSection direction="up">
        <div
          className="w-full px-6"
          style={{
            paddingTop: 'clamp(80px, 8vw, 120px)',
            paddingBottom: 'clamp(80px, 8vw, 120px)',
            background: 'linear-gradient(135deg, #1B45B4 0%, #0D1A7A 100%)',
          }}
        >
          <div className="text-center mx-auto" style={{ maxWidth: 'min(900px, 90%)' }}>
            <h2
              className="font-dm-sans font-bold tracking-[-0.03em] text-white mb-6"
              style={{
                fontSize: 'clamp(32px, 3.5vw, 56px)',
                lineHeight: '105%',
              }}
            >
              Stop Guessing. Start Allocating with Precision.
            </h2>

            <p
              className="font-dm-sans font-normal text-white mb-8"
              style={{
                fontSize: 'clamp(15px, 1.375vw, 19.8px)',
                lineHeight: '1.6',
                opacity: 0.8,
              }}
            >
              Eliminate gut-driven capital allocation. Engage with our team to implement the BVU Model and bring quantitative, auditable clarity to your most critical investment and resource decisions.
            </p>

            <Link
              href="/contact-us"
              className="inline-flex items-center gap-2 font-dm-sans font-medium rounded-[8px] transition-opacity hover:opacity-90"
              style={{
                backgroundColor: 'rgba(255, 255, 255, 0.2)',
                color: 'white',
                fontSize: 'clamp(15px, 1.375vw, 19.8px)',
                padding: '12px 28px',
                border: '2px solid rgba(255, 255, 255, 0.3)',
              }}
            >
              Request a Consultation <MoveRight size={20} />
            </Link>
          </div>
        </div>
      </FadeInSection>

      <Footer />
    </main>
  );
}
